services:
  sam:
    build: .
    tty: true
    #entrypoint: sam local start-api --host 0.0.0.0 --debug --container-host host.docker.internal --container-host-interface 0.0.0.0 -n "$PWD/global.env.json"
    entrypoint: sam local start-api --host 0.0.0.0 --debug --container-host host.docker.internal --container-host-interface 0.0.0.0 -n "$PWD/env.json"
    working_dir: $PWD
    ports:
      - 3000:3000
    volumes:
      - $PWD:/root
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    environment:
      - FOO_COMPOSE=docker-compose_set
